"use client";
import { useAuth } from "@/lib/auth-context";
import { motion } from "framer-motion";
import { Lightbulb, ShieldAlert, CheckCircle2, Activity, Zap } from "lucide-react";
import { useState, useEffect } from "react";

const fadeUp = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0 } };
const stagger = { show: { transition: { staggerChildren: 0.05 } } };

export default function RecommendationsPage() {
  const { user } = useAuth();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.email) {
      fetch(`http://localhost:9000/user/recommendations?email=${encodeURIComponent(user.email)}`)
        .then(res => res.json())
        .then(res => { setData(res); setLoading(false); })
        .catch(err => { console.error(err); setLoading(false); });
    }
  }, [user]);

  if (!user) return null;
  if (loading) return <div className="flex items-center justify-center h-96"><Activity className="w-8 h-8 text-brand-500 animate-spin" /></div>;

  const recs = data?.recommendations || [];

  return (
    <motion.div variants={stagger} initial="hidden" animate="show" className="space-y-6 max-w-4xl mx-auto">
      <motion.div variants={fadeUp}>
        <h1 className="text-2xl font-bold flex items-center gap-2 text-surface-900 dark:text-white">
          <Lightbulb className="w-6 h-6 text-brand-650 dark:text-brand-400" /> Security Recommendations
        </h1>
        <p className="text-sm text-surface-500 dark:text-surface-400 mt-1">Personalized, actionable tips generated by AI based on your browsing behavior.</p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {recs.map((rec: any) => (
          <motion.div key={rec.id} variants={fadeUp} className="stat-card flex flex-col relative overflow-hidden group">
            <div className={`absolute top-0 right-0 w-32 h-32 blur-[60px] -mr-10 -mt-10 opacity-20 pointer-events-none ${
              rec.type === 'critical' ? 'bg-red-500' : rec.type === 'action' ? 'bg-brand-500' : 'bg-amber-500'
            }`} />
            
            <div className="flex items-start gap-3 mb-3 relative z-10">
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${
                rec.type === 'critical' ? 'bg-red-500/10 text-red-500' : 
                rec.type === 'action' ? 'bg-brand-500/10 text-brand-500' : 'bg-amber-500/10 text-amber-500'
              }`}>
                {rec.type === 'critical' ? <ShieldAlert className="w-5 h-5" /> : 
                 rec.type === 'action' ? <Zap className="w-5 h-5" /> : <CheckCircle2 className="w-5 h-5" />}
              </div>
              <div>
                <h3 className="font-bold text-surface-900 dark:text-white">{rec.title}</h3>
                <span className={`text-[10px] font-bold uppercase tracking-wider ${
                  rec.type === 'critical' ? 'text-red-500' : rec.type === 'action' ? 'text-brand-500' : 'text-amber-500'
                }`}>
                  {rec.type} Priority
                </span>
              </div>
            </div>
            
            <p className="text-sm text-surface-600 dark:text-surface-400 relative z-10 flex-1">
              {rec.desc}
            </p>
            
            <div className="mt-4 pt-3 border-t border-surface-200 dark:border-white/[0.05] relative z-10">
              <button className="text-xs font-semibold text-brand-600 dark:text-brand-400 hover:underline">Learn how to fix this &rarr;</button>
            </div>
          </motion.div>
        ))}
      </div>
    </motion.div>
  );
}
